# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 03:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('copy_cat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenname',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
    ]
