# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 08:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copy_cat', '0002_screenname_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bot',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='ScreenName',
        ),
    ]
